[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
deorg_voting_program = "EGnx6SNyQkF2rxXc2uGwVVkZUMoFVfGQWNe18jzapx2h"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://devnet.helius-rpc.com?api-key="
wallet = "deorg_voting_program-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
